// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Display Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.display_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    display_title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = TitleText1Slice | InfoStatusImage1Slice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = PageDocument;
/**
 * Primary content in InfoStatsImage1 → Primary
 *
 */
interface InfoStatusImage1SliceDefaultPrimary {
    /**
     * Top title field in *InfoStatsImage1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    top_title: prismicT.TitleField;
    /**
     * Title field in *InfoStatsImage1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *InfoStatsImage1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Link Name field in *InfoStatsImage1 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *InfoStatsImage1 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Image field in *InfoStatsImage1 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"tablet" | "mobile" | "desktop">;
}
/**
 * Item in InfoStatsImage1 → Items
 *
 */
export interface InfoStatusImage1SliceDefaultItem {
    /**
     * Stat Number field in *InfoStatsImage1 → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_number
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    stat_number: prismicT.NumberField;
    /**
     * Stat Suffix field in *InfoStatsImage1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_suffix
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    stat_suffix: prismicT.KeyTextField;
    /**
     * Stat Name field in *InfoStatsImage1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    stat_name: prismicT.KeyTextField;
}
/**
 * Default variation for InfoStatsImage1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `InfoStatusImage1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStatusImage1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<InfoStatusImage1SliceDefaultPrimary>, Simplify<InfoStatusImage1SliceDefaultItem>>;
/**
 * Slice variation for *InfoStatsImage1*
 *
 */
type InfoStatusImage1SliceVariation = InfoStatusImage1SliceDefault;
/**
 * InfoStatsImage1 Shared Slice
 *
 * - **API ID**: `info_status_image1`
 * - **Description**: `InfoStatusImage1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStatusImage1Slice = prismicT.SharedSlice<"info_status_image1", InfoStatusImage1SliceVariation>;
/**
 * Primary content in TitleText1 → Primary
 *
 */
interface TitleText1SliceDefaultPrimary {
    /**
     * Title field in *TitleText1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: title_text1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *TitleText1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_text1.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for TitleText1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TitleText1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleText1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TitleText1SliceDefaultPrimary>, never>;
/**
 * Slice variation for *TitleText1*
 *
 */
type TitleText1SliceVariation = TitleText1SliceDefault;
/**
 * TitleText1 Shared Slice
 *
 * - **API ID**: `title_text1`
 * - **Description**: `TitleText1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleText1Slice = prismicT.SharedSlice<"title_text1", TitleText1SliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, InfoStatusImage1SliceDefaultPrimary, InfoStatusImage1SliceDefaultItem, InfoStatusImage1SliceDefault, InfoStatusImage1SliceVariation, InfoStatusImage1Slice, TitleText1SliceDefaultPrimary, TitleText1SliceDefault, TitleText1SliceVariation, TitleText1Slice };
    }
}
