// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Display Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.display_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    display_title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = TitleText1Slice | InfoStatusImage1Slice | VideoDescriptionLauncherSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = PageDocument;
/**
 * Primary content in Info1 → Primary
 *
 */
interface InfoStatusImage1SliceDefaultPrimary {
    /**
     * Top title field in *Info1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    top_title: prismicT.TitleField;
    /**
     * Title field in *Info1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *Info1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Link Name field in *Info1 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *Info1 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Image field in *Info1 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"tablet" | "mobile" | "desktop">;
}
/**
 * Item in Info1 → Items
 *
 */
export interface InfoStatusImage1SliceDefaultItem {
    /**
     * Stat Number field in *Info1 → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_number
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    stat_number: prismicT.NumberField;
    /**
     * Stat Suffix field in *Info1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_suffix
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    stat_suffix: prismicT.KeyTextField;
    /**
     * Stat Name field in *Info1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    stat_name: prismicT.KeyTextField;
}
/**
 * Default variation for Info1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `InfoStatusImage1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStatusImage1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<InfoStatusImage1SliceDefaultPrimary>, Simplify<InfoStatusImage1SliceDefaultItem>>;
/**
 * Slice variation for *Info1*
 *
 */
type InfoStatusImage1SliceVariation = InfoStatusImage1SliceDefault;
/**
 * Info1 Shared Slice
 *
 * - **API ID**: `info_status_image1`
 * - **Description**: `InfoStatusImage1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStatusImage1Slice = prismicT.SharedSlice<"info_status_image1", InfoStatusImage1SliceVariation>;
/**
 * Primary content in Info2 → Primary
 *
 */
interface InfoStats2SliceDefaultPrimary {
    /**
     * Top Title field in *Info2 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    top_title: prismicT.KeyTextField;
    /**
     * Title field in *Info2 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Content field in *Info2 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Image 1 field in *Info2 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.image_1
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_1: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Image 2 field in *Info2 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.image_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_2: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Image 1 field in *Info2 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.image_3
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_3: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
}
/**
 * Item in Info2 → Items
 *
 */
export interface InfoStats2SliceDefaultItem {
    /**
     * Feature Icon field in *Info2 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Icon name
     * - **API ID Path**: info_stats2.items[].feature_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    feature_icon: prismicT.KeyTextField;
    /**
     * Feature Name field in *Info2 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.items[].feature_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    feature_name: prismicT.KeyTextField;
}
/**
 * Default variation for Info2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `InfoStats2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStats2SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<InfoStats2SliceDefaultPrimary>, Simplify<InfoStats2SliceDefaultItem>>;
/**
 * Slice variation for *Info2*
 *
 */
type InfoStats2SliceVariation = InfoStats2SliceDefault;
/**
 * Info2 Shared Slice
 *
 * - **API ID**: `info_stats2`
 * - **Description**: `InfoStats2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStats2Slice = prismicT.SharedSlice<"info_stats2", InfoStats2SliceVariation>;
/**
 * Primary content in Info3 → Primary
 *
 */
interface ImagesInfoData2SliceDefaultPrimary {
    /**
     * Title field in *Info3 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *Info3 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Link Name field in *Info3 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *Info3 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Image 1 field in *Info3 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.image_1
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_1: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Image 2 field in *Info3 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.image_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_2: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Caption Title field in *Info3 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.caption_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_title: prismicT.TitleField;
    /**
     * Caption Description field in *Info3 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.caption_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_description: prismicT.TitleField;
    /**
     * Separator field in *Info3 → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: images_info_data2.primary.separator
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    separator: prismicT.BooleanField;
}
/**
 * Default variation for Info3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImagesInfoData2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImagesInfoData2SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImagesInfoData2SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Info3*
 *
 */
type ImagesInfoData2SliceVariation = ImagesInfoData2SliceDefault;
/**
 * Info3 Shared Slice
 *
 * - **API ID**: `images_info_data2`
 * - **Description**: `ImagesInfoData2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImagesInfoData2Slice = prismicT.SharedSlice<"images_info_data2", ImagesInfoData2SliceVariation>;
/**
 * Primary content in Info4 → Primary
 *
 */
interface VideoDescriptionLauncherSliceDefaultPrimary {
    /**
     * Title field in *Info4 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *Info4 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.TitleField;
    /**
     * Video field in *Info4 → Primary*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.video
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    video: prismicT.EmbedField;
    /**
     * Image field in *Info4 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Caption Title field in *Info4 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.caption_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_title: prismicT.TitleField;
    /**
     * Caption Description field in *Info4 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.caption_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_description: prismicT.RichTextField;
}
/**
 * Default variation for Info4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `VideoDescriptionLauncher`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoDescriptionLauncherSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<VideoDescriptionLauncherSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Info4*
 *
 */
type VideoDescriptionLauncherSliceVariation = VideoDescriptionLauncherSliceDefault;
/**
 * Info4 Shared Slice
 *
 * - **API ID**: `video_description_launcher`
 * - **Description**: `VideoDescriptionLauncher`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoDescriptionLauncherSlice = prismicT.SharedSlice<"video_description_launcher", VideoDescriptionLauncherSliceVariation>;
/**
 * Primary content in Info5 → Primary
 *
 */
interface ProgressInfo1SliceDefaultPrimary {
    /**
     * Title field in *Info5 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *Info5 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.TitleField;
    /**
     * Content field in *Info5 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Image field in *Info5 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
}
/**
 * Item in Info5 → Items
 *
 */
export interface ProgressInfo1SliceDefaultItem {
    /**
     * Progress Title field in *Info5 → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.items[].progress_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    progress_title: prismicT.TitleField;
    /**
     * Progress percentage field in *Info5 → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: from 0 to 100
     * - **API ID Path**: progress_info1.items[].progress_percentage
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    progress_percentage: prismicT.NumberField;
}
/**
 * Default variation for Info5 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProgressInfo1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProgressInfo1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProgressInfo1SliceDefaultPrimary>, Simplify<ProgressInfo1SliceDefaultItem>>;
/**
 * Slice variation for *Info5*
 *
 */
type ProgressInfo1SliceVariation = ProgressInfo1SliceDefault;
/**
 * Info5 Shared Slice
 *
 * - **API ID**: `progress_info1`
 * - **Description**: `ProgressInfo1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProgressInfo1Slice = prismicT.SharedSlice<"progress_info1", ProgressInfo1SliceVariation>;
/**
 * Primary content in Info6 → Primary
 *
 */
interface Info6SliceDefaultPrimary {
    /**
     * Top Title field in *Info6 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    top_title: prismicT.TitleField;
    /**
     * Title field in *Info6 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *Info6 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Link Name field in *Info6 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *Info6 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Caption Title field in *Info6 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.caption_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_title: prismicT.TitleField;
    /**
     * Caption Description field in *Info6 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.caption_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_description: prismicT.RichTextField;
    /**
     * Background Image field in *Info6 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
}
/**
 * Default variation for Info6 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Info6`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Info6SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Info6SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Info6*
 *
 */
type Info6SliceVariation = Info6SliceDefault;
/**
 * Info6 Shared Slice
 *
 * - **API ID**: `info6`
 * - **Description**: `Info6`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Info6Slice = prismicT.SharedSlice<"info6", Info6SliceVariation>;
/**
 * Primary content in InfoSimple → Primary
 *
 */
interface TitleText1SliceDefaultPrimary {
    /**
     * Title field in *InfoSimple → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: title_text1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *InfoSimple → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_text1.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for InfoSimple Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TitleText1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleText1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TitleText1SliceDefaultPrimary>, never>;
/**
 * Slice variation for *InfoSimple*
 *
 */
type TitleText1SliceVariation = TitleText1SliceDefault;
/**
 * InfoSimple Shared Slice
 *
 * - **API ID**: `title_text1`
 * - **Description**: `TitleText1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleText1Slice = prismicT.SharedSlice<"title_text1", TitleText1SliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, InfoStatusImage1SliceDefaultPrimary, InfoStatusImage1SliceDefaultItem, InfoStatusImage1SliceDefault, InfoStatusImage1SliceVariation, InfoStatusImage1Slice, InfoStats2SliceDefaultPrimary, InfoStats2SliceDefaultItem, InfoStats2SliceDefault, InfoStats2SliceVariation, InfoStats2Slice, ImagesInfoData2SliceDefaultPrimary, ImagesInfoData2SliceDefault, ImagesInfoData2SliceVariation, ImagesInfoData2Slice, VideoDescriptionLauncherSliceDefaultPrimary, VideoDescriptionLauncherSliceDefault, VideoDescriptionLauncherSliceVariation, VideoDescriptionLauncherSlice, ProgressInfo1SliceDefaultPrimary, ProgressInfo1SliceDefaultItem, ProgressInfo1SliceDefault, ProgressInfo1SliceVariation, ProgressInfo1Slice, Info6SliceDefaultPrimary, Info6SliceDefault, Info6SliceVariation, Info6Slice, TitleText1SliceDefaultPrimary, TitleText1SliceDefault, TitleText1SliceVariation, TitleText1Slice };
    }
}
