// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Brand Info documents */
interface BrandInfoDocumentData {
    /**
     * Brand Name field in *Brand Info*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.brand_name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    brand_name: prismicT.KeyTextField;
    /**
     * Logo field in *Brand Info*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * Logo negative field in *Brand Info*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.logo_negative
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo_negative: prismicT.ImageField<never>;
    /**
     * Phones field in *Brand Info*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.phone_number[]
     * - **Tab**: Phones
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    phone_number: prismicT.GroupField<Simplify<BrandInfoDocumentDataPhoneNumberItem>>;
    /**
     * Addresses  field in *Brand Info*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.addresses[]
     * - **Tab**: Addresses
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    addresses: prismicT.GroupField<Simplify<BrandInfoDocumentDataAddressesItem>>;
    /**
     * Mails field in *Brand Info*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.mails[]
     * - **Tab**: Mails
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    mails: prismicT.GroupField<Simplify<BrandInfoDocumentDataMailsItem>>;
    /**
     * Social Media field in *Brand Info*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.social_media[]
     * - **Tab**: Social Media
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social_media: prismicT.GroupField<Simplify<BrandInfoDocumentDataSocialMediaItem>>;
}
/**
 * Item in Brand Info → Phones
 *
 */
export interface BrandInfoDocumentDataPhoneNumberItem {
    /**
     * Number field in *Brand Info → Phones*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.phone_number[].phone_number
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    phone_number: prismicT.KeyTextField;
    /**
     * Zone field in *Brand Info → Phones*
     *
     * - **Field Type**: GeoPoint
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.phone_number[].zone
     * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
     *
     */
    zone: prismicT.GeoPointField;
    /**
     * Name field in *Brand Info → Phones*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.phone_number[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
}
/**
 * Item in Brand Info → Addresses
 *
 */
export interface BrandInfoDocumentDataAddressesItem {
    /**
     * Address field in *Brand Info → Addresses *
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.addresses[].address
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    address: prismicT.KeyTextField;
    /**
     * Zone field in *Brand Info → Addresses *
     *
     * - **Field Type**: GeoPoint
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.addresses[].zone
     * - **Documentation**: https://prismic.io/docs/core-concepts/geopoint
     *
     */
    zone: prismicT.GeoPointField;
    /**
     * Name field in *Brand Info → Addresses *
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.addresses[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
}
/**
 * Item in Brand Info → Mails
 *
 */
export interface BrandInfoDocumentDataMailsItem {
    /**
     * Mail field in *Brand Info → Mails*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.mails[].mail
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    mail: prismicT.KeyTextField;
}
/**
 * Item in Brand Info → Social Media
 *
 */
export interface BrandInfoDocumentDataSocialMediaItem {
    /**
     * Name field in *Brand Info → Social Media*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.social_media[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Icon field in *Brand Info → Social Media*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.social_media[].icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    icon: prismicT.KeyTextField;
    /**
     * Link field in *Brand Info → Social Media*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: brand_info.social_media[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Brand Info document from Prismic
 *
 * - **API ID**: `brand_info`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrandInfoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<BrandInfoDocumentData>, "brand_info", Lang>;
/** Content for Intro documents */
interface IntroDocumentData {
    /**
     * Slides field in *Intro*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.slides[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    slides: prismicT.GroupField<Simplify<IntroDocumentDataSlidesItem>>;
    /**
     * Slice Zone field in *Intro*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<IntroDocumentDataSlicesSlice>;
}
/**
 * Item in Intro → Slides
 *
 */
export interface IntroDocumentDataSlidesItem {
    /**
     * Title Top field in *Intro → Slides*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.slides[].title_top
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_top: prismicT.TitleField;
    /**
     * Title Bottom field in *Intro → Slides*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.slides[].title_bottom
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title_bottom: prismicT.TitleField;
    /**
     * Image field in *Intro → Slides*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.slides[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Link Url field in *Intro → Slides*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.slides[].link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Link Name field in *Intro → Slides*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro.slides[].link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    link_name: prismicT.RichTextField;
}
/**
 * Slice for *Intro → Slice Zone*
 *
 */
type IntroDocumentDataSlicesSlice = never;
/**
 * Intro document from Prismic
 *
 * - **API ID**: `intro`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IntroDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<IntroDocumentData>, "intro", Lang>;
/** Content for Navigation documents */
interface NavbarDocumentData {
    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavbarDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavbarDocumentDataSlicesSlice = NavigationItemSlice;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavbarDocumentData>, "navbar", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Display Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.display_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    display_title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = InfoStatusImage1Slice | Cta1Slice | Carousel1Slice | IconLinksSlice | ImagesInfoData2Slice | InfoStats2Slice | Info6Slice | ProgressInfo1Slice | VideoDescriptionLauncherSlice | TitleText1Slice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = BrandInfoDocument | IntroDocument | NavbarDocument | PageDocument;
/**
 * Item in Carousel1 → Items
 *
 */
export interface Carousel1SliceDefaultItem {
    /**
     * Tag field in *Carousel1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel1.items[].tag
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tag: prismicT.KeyTextField;
    /**
     * Top Title field in *Carousel1 → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel1.items[].top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    top_title: prismicT.TitleField;
    /**
     * Title field in *Carousel1 → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel1.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Image field in *Carousel1 → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel1.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Link url field in *Carousel1 → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: carousel1.items[].link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
}
/**
 * Default variation for Carousel1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Carousel1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Carousel1SliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<Carousel1SliceDefaultItem>>;
/**
 * Slice variation for *Carousel1*
 *
 */
type Carousel1SliceVariation = Carousel1SliceDefault;
/**
 * Carousel1 Shared Slice
 *
 * - **API ID**: `carousel1`
 * - **Description**: `Carousel1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Carousel1Slice = prismicT.SharedSlice<"carousel1", Carousel1SliceVariation>;
/**
 * Primary content in Cta1 → Primary
 *
 */
interface Cta1SliceDefaultPrimary {
    /**
     * Top Title field in *Cta1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: cta1.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    top_title: prismicT.TitleField;
    /**
     * Link Name field in *Cta1 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cta1.primary.link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *Cta1 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: cta1.primary.link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Background Image field in *Cta1 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cta1.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
}
/**
 * Item in Cta1 → Items
 *
 */
export interface Cta1SliceDefaultItem {
    /**
     * Text field in *Cta1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cta1.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
    /**
     * Style field in *Cta1 → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: cta1.items[].style
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    style: prismicT.SelectField<"outline" | "back color">;
}
/**
 * Default variation for Cta1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Cta1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Cta1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Cta1SliceDefaultPrimary>, Simplify<Cta1SliceDefaultItem>>;
/**
 * Slice variation for *Cta1*
 *
 */
type Cta1SliceVariation = Cta1SliceDefault;
/**
 * Cta1 Shared Slice
 *
 * - **API ID**: `cta1`
 * - **Description**: `Cta1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Cta1Slice = prismicT.SharedSlice<"cta1", Cta1SliceVariation>;
/**
 * Primary content in IconLinks → Primary
 *
 */
interface IconLinksSliceDefaultPrimary {
    /**
     * Top Title field in *IconLinks → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: icon_links.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    top_title: prismicT.TitleField;
    /**
     * Title field in *IconLinks → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: icon_links.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *IconLinks → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Item in IconLinks → Items
 *
 */
export interface IconLinksSliceDefaultItem {
    /**
     * Light Theme Image field in *IconLinks → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].light_theme_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    light_theme_image: prismicT.ImageField<never>;
    /**
     * Dark Theme Image field in *IconLinks → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].dark_theme_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    dark_theme_image: prismicT.ImageField<never>;
    /**
     * Link Name field in *IconLinks → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *IconLinks → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
}
/**
 * Default variation for IconLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `IconLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IconLinksSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<IconLinksSliceDefaultPrimary>, Simplify<IconLinksSliceDefaultItem>>;
/**
 * Primary content in IconLinks → Primary
 *
 */
interface IconLinksSliceIconsLinkIconsOnlyPrimary {
    /**
     * Center Items field in *IconLinks → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: icon_links.primary.center_items
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    center_items: prismicT.BooleanField;
}
/**
 * Item in IconLinks → Items
 *
 */
export interface IconLinksSliceIconsLinkIconsOnlyItem {
    /**
     * Light Theme Image field in *IconLinks → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].light_theme_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    light_theme_image: prismicT.ImageField<never>;
    /**
     * Dark Theme Image field in *IconLinks → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].dark_theme_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    dark_theme_image: prismicT.ImageField<never>;
    /**
     * Link Name field in *IconLinks → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *IconLinks → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
}
/**
 * IconsLink - Icons Only variation for IconLinks Slice
 *
 * - **API ID**: `iconsLinkIconsOnly`
 * - **Description**: `IconLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IconLinksSliceIconsLinkIconsOnly = prismicT.SharedSliceVariation<"iconsLinkIconsOnly", Simplify<IconLinksSliceIconsLinkIconsOnlyPrimary>, Simplify<IconLinksSliceIconsLinkIconsOnlyItem>>;
/**
 * Primary content in IconLinks → Primary
 *
 */
interface IconLinksSliceTopContentPrimary {
    /**
     * Title field in *IconLinks → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: icon_links.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *IconLinks → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Background Details field in *IconLinks → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: icon_links.primary.background_details
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    background_details: prismicT.BooleanField;
}
/**
 * Item in IconLinks → Items
 *
 */
export interface IconLinksSliceTopContentItem {
    /**
     * Image field in *IconLinks → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].dark_theme_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    dark_theme_image: prismicT.ImageField<never>;
    /**
     * Link Name field in *IconLinks → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *IconLinks → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: icon_links.items[].link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Hide on Mobile field in *IconLinks → Items*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: icon_links.items[].hideOnMobile
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    hideOnMobile: prismicT.BooleanField;
}
/**
 * TopContent variation for IconLinks Slice
 *
 * - **API ID**: `topContent`
 * - **Description**: `IconLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IconLinksSliceTopContent = prismicT.SharedSliceVariation<"topContent", Simplify<IconLinksSliceTopContentPrimary>, Simplify<IconLinksSliceTopContentItem>>;
/**
 * Slice variation for *IconLinks*
 *
 */
type IconLinksSliceVariation = IconLinksSliceDefault | IconLinksSliceIconsLinkIconsOnly | IconLinksSliceTopContent;
/**
 * IconLinks Shared Slice
 *
 * - **API ID**: `icon_links`
 * - **Description**: `IconLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IconLinksSlice = prismicT.SharedSlice<"icon_links", IconLinksSliceVariation>;
/**
 * Primary content in Info1 → Primary
 *
 */
interface InfoStatusImage1SliceDefaultPrimary {
    /**
     * Top title field in *Info1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    top_title: prismicT.TitleField;
    /**
     * Title field in *Info1 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *Info1 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Link Name field in *Info1 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *Info1 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Image field in *Info1 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"tablet" | "mobile" | "desktop">;
}
/**
 * Item in Info1 → Items
 *
 */
export interface InfoStatusImage1SliceDefaultItem {
    /**
     * Stat Number field in *Info1 → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_number
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    stat_number: prismicT.NumberField;
    /**
     * Stat Suffix field in *Info1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_suffix
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    stat_suffix: prismicT.KeyTextField;
    /**
     * Stat Name field in *Info1 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_status_image1.items[].stat_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    stat_name: prismicT.KeyTextField;
}
/**
 * Default variation for Info1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `InfoStatusImage1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStatusImage1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<InfoStatusImage1SliceDefaultPrimary>, Simplify<InfoStatusImage1SliceDefaultItem>>;
/**
 * Slice variation for *Info1*
 *
 */
type InfoStatusImage1SliceVariation = InfoStatusImage1SliceDefault;
/**
 * Info1 Shared Slice
 *
 * - **API ID**: `info_status_image1`
 * - **Description**: `InfoStatusImage1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStatusImage1Slice = prismicT.SharedSlice<"info_status_image1", InfoStatusImage1SliceVariation>;
/**
 * Primary content in Info2 → Primary
 *
 */
interface InfoStats2SliceDefaultPrimary {
    /**
     * Top Title field in *Info2 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    top_title: prismicT.KeyTextField;
    /**
     * Title field in *Info2 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Content field in *Info2 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Image 1 field in *Info2 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.image_1
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_1: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Image 2 field in *Info2 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.image_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_2: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Image 1 field in *Info2 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.primary.image_3
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_3: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
}
/**
 * Item in Info2 → Items
 *
 */
export interface InfoStats2SliceDefaultItem {
    /**
     * Feature Icon field in *Info2 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Icon name
     * - **API ID Path**: info_stats2.items[].feature_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    feature_icon: prismicT.KeyTextField;
    /**
     * Feature Name field in *Info2 → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info_stats2.items[].feature_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    feature_name: prismicT.KeyTextField;
}
/**
 * Default variation for Info2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `InfoStats2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStats2SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<InfoStats2SliceDefaultPrimary>, Simplify<InfoStats2SliceDefaultItem>>;
/**
 * Slice variation for *Info2*
 *
 */
type InfoStats2SliceVariation = InfoStats2SliceDefault;
/**
 * Info2 Shared Slice
 *
 * - **API ID**: `info_stats2`
 * - **Description**: `InfoStats2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type InfoStats2Slice = prismicT.SharedSlice<"info_stats2", InfoStats2SliceVariation>;
/**
 * Primary content in Info3 → Primary
 *
 */
interface ImagesInfoData2SliceDefaultPrimary {
    /**
     * Title field in *Info3 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *Info3 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Link Name field in *Info3 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *Info3 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Image 1 field in *Info3 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.image_1
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_1: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Image 2 field in *Info3 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.image_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image_2: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Caption Title field in *Info3 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.caption_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_title: prismicT.TitleField;
    /**
     * Caption Description field in *Info3 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: images_info_data2.primary.caption_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_description: prismicT.TitleField;
    /**
     * Separator field in *Info3 → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: true
     * - **API ID Path**: images_info_data2.primary.separator
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    separator: prismicT.BooleanField;
}
/**
 * Default variation for Info3 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImagesInfoData2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImagesInfoData2SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImagesInfoData2SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Info3*
 *
 */
type ImagesInfoData2SliceVariation = ImagesInfoData2SliceDefault;
/**
 * Info3 Shared Slice
 *
 * - **API ID**: `images_info_data2`
 * - **Description**: `ImagesInfoData2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImagesInfoData2Slice = prismicT.SharedSlice<"images_info_data2", ImagesInfoData2SliceVariation>;
/**
 * Primary content in Info4 → Primary
 *
 */
interface VideoDescriptionLauncherSliceDefaultPrimary {
    /**
     * Title field in *Info4 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *Info4 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.TitleField;
    /**
     * Video field in *Info4 → Primary*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.video
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    video: prismicT.EmbedField;
    /**
     * Image field in *Info4 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
    /**
     * Caption Title field in *Info4 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.caption_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_title: prismicT.TitleField;
    /**
     * Caption Description field in *Info4 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_description_launcher.primary.caption_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_description: prismicT.RichTextField;
}
/**
 * Default variation for Info4 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `VideoDescriptionLauncher`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoDescriptionLauncherSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<VideoDescriptionLauncherSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Info4*
 *
 */
type VideoDescriptionLauncherSliceVariation = VideoDescriptionLauncherSliceDefault;
/**
 * Info4 Shared Slice
 *
 * - **API ID**: `video_description_launcher`
 * - **Description**: `VideoDescriptionLauncher`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoDescriptionLauncherSlice = prismicT.SharedSlice<"video_description_launcher", VideoDescriptionLauncherSliceVariation>;
/**
 * Primary content in Info5 → Primary
 *
 */
interface ProgressInfo1SliceDefaultPrimary {
    /**
     * Title field in *Info5 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *Info5 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.TitleField;
    /**
     * Content field in *Info5 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Image field in *Info5 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
}
/**
 * Item in Info5 → Items
 *
 */
export interface ProgressInfo1SliceDefaultItem {
    /**
     * Progress Title field in *Info5 → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: progress_info1.items[].progress_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    progress_title: prismicT.TitleField;
    /**
     * Progress percentage field in *Info5 → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: from 0 to 100
     * - **API ID Path**: progress_info1.items[].progress_percentage
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    progress_percentage: prismicT.NumberField;
}
/**
 * Default variation for Info5 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProgressInfo1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProgressInfo1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProgressInfo1SliceDefaultPrimary>, Simplify<ProgressInfo1SliceDefaultItem>>;
/**
 * Slice variation for *Info5*
 *
 */
type ProgressInfo1SliceVariation = ProgressInfo1SliceDefault;
/**
 * Info5 Shared Slice
 *
 * - **API ID**: `progress_info1`
 * - **Description**: `ProgressInfo1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProgressInfo1Slice = prismicT.SharedSlice<"progress_info1", ProgressInfo1SliceVariation>;
/**
 * Primary content in Info6 → Primary
 *
 */
interface Info6SliceDefaultPrimary {
    /**
     * Top Title field in *Info6 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.top_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    top_title: prismicT.TitleField;
    /**
     * Title field in *Info6 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *Info6 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Link Name field in *Info6 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.link_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_name: prismicT.KeyTextField;
    /**
     * Link Url field in *Info6 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.link_url
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_url: prismicT.LinkField;
    /**
     * Caption Title field in *Info6 → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.caption_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_title: prismicT.TitleField;
    /**
     * Caption Description field in *Info6 → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.caption_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption_description: prismicT.RichTextField;
    /**
     * Background Image field in *Info6 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: info6.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<"desktop" | "tablet" | "mobile">;
}
/**
 * Default variation for Info6 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Info6`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Info6SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Info6SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Info6*
 *
 */
type Info6SliceVariation = Info6SliceDefault;
/**
 * Info6 Shared Slice
 *
 * - **API ID**: `info6`
 * - **Description**: `Info6`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Info6Slice = prismicT.SharedSlice<"info6", Info6SliceVariation>;
/**
 * Primary content in InfoSimple → Primary
 *
 */
interface TitleText1SliceDefaultPrimary {
    /**
     * Title field in *InfoSimple → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: title_text1.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *InfoSimple → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_text1.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for InfoSimple Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TitleText1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleText1SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TitleText1SliceDefaultPrimary>, never>;
/**
 * Slice variation for *InfoSimple*
 *
 */
type TitleText1SliceVariation = TitleText1SliceDefault;
/**
 * InfoSimple Shared Slice
 *
 * - **API ID**: `title_text1`
 * - **Description**: `TitleText1`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleText1Slice = prismicT.SharedSlice<"title_text1", TitleText1SliceVariation>;
/**
 * Primary content in NavigationItem → Primary
 *
 */
interface NavigationItemSliceDefaultPrimary {
    /**
     * Item Name field in *NavigationItem → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.primary.item_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item_name: prismicT.KeyTextField;
    /**
     * Item Link field in *NavigationItem → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.primary.item_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    item_link: prismicT.LinkField;
}
/**
 * Item in NavigationItem → Items
 *
 */
export interface NavigationItemSliceDefaultItem {
    /**
     * Sub Item Name field in *NavigationItem → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.items[].sub_item_name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    sub_item_name: prismicT.KeyTextField;
    /**
     * Sub Item Link field in *NavigationItem → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_item.items[].sub_item_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    sub_item_link: prismicT.LinkField;
}
/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<NavigationItemSliceDefaultPrimary>, Simplify<NavigationItemSliceDefaultItem>>;
/**
 * Slice variation for *NavigationItem*
 *
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;
/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSlice = prismicT.SharedSlice<"navigation_item", NavigationItemSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { BrandInfoDocumentData, BrandInfoDocumentDataPhoneNumberItem, BrandInfoDocumentDataAddressesItem, BrandInfoDocumentDataMailsItem, BrandInfoDocumentDataSocialMediaItem, BrandInfoDocument, IntroDocumentData, IntroDocumentDataSlidesItem, IntroDocumentDataSlicesSlice, IntroDocument, NavbarDocumentData, NavbarDocumentDataSlicesSlice, NavbarDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, Carousel1SliceDefaultItem, Carousel1SliceDefault, Carousel1SliceVariation, Carousel1Slice, Cta1SliceDefaultPrimary, Cta1SliceDefaultItem, Cta1SliceDefault, Cta1SliceVariation, Cta1Slice, IconLinksSliceDefaultPrimary, IconLinksSliceDefaultItem, IconLinksSliceDefault, IconLinksSliceIconsLinkIconsOnlyPrimary, IconLinksSliceIconsLinkIconsOnlyItem, IconLinksSliceIconsLinkIconsOnly, IconLinksSliceTopContentPrimary, IconLinksSliceTopContentItem, IconLinksSliceTopContent, IconLinksSliceVariation, IconLinksSlice, InfoStatusImage1SliceDefaultPrimary, InfoStatusImage1SliceDefaultItem, InfoStatusImage1SliceDefault, InfoStatusImage1SliceVariation, InfoStatusImage1Slice, InfoStats2SliceDefaultPrimary, InfoStats2SliceDefaultItem, InfoStats2SliceDefault, InfoStats2SliceVariation, InfoStats2Slice, ImagesInfoData2SliceDefaultPrimary, ImagesInfoData2SliceDefault, ImagesInfoData2SliceVariation, ImagesInfoData2Slice, VideoDescriptionLauncherSliceDefaultPrimary, VideoDescriptionLauncherSliceDefault, VideoDescriptionLauncherSliceVariation, VideoDescriptionLauncherSlice, ProgressInfo1SliceDefaultPrimary, ProgressInfo1SliceDefaultItem, ProgressInfo1SliceDefault, ProgressInfo1SliceVariation, ProgressInfo1Slice, Info6SliceDefaultPrimary, Info6SliceDefault, Info6SliceVariation, Info6Slice, TitleText1SliceDefaultPrimary, TitleText1SliceDefault, TitleText1SliceVariation, TitleText1Slice, NavigationItemSliceDefaultPrimary, NavigationItemSliceDefaultItem, NavigationItemSliceDefault, NavigationItemSliceVariation, NavigationItemSlice };
    }
}
