// Code generated by Slice Machine. DO NOT EDIT.

import Carousel1 from './Carousel1';
import Cta1 from './Cta1';
import IconLinks from './IconLinks';
import Info1 from './Info1';
import Info2 from './Info2';
import Info3 from './Info3';
import Info4 from './Info4';
import Info5 from './Info5';
import Info6 from './Info6';
import InfoSimple from './InfoSimple';

export {
	Carousel1,
	Cta1,
	IconLinks,
	Info1,
	Info2,
	Info3,
	Info4,
	Info5,
	Info6,
	InfoSimple,
};

export const components = {
	carousel1: Carousel1,
	cta1: Cta1,
	icon_links: IconLinks,
	info_status_image1: Info1,
	info_stats2: Info2,
	images_info_data2: Info3,
	video_description_launcher: Info4,
	progress_info1: Info5,
	info6: Info6,
	title_text1: InfoSimple,
};
