// Code generated by Slice Machine. DO NOT EDIT.

import InfoStatsImage1 from './InfoStatsImage1';
import TitleText1 from './TitleText1';

export {
	InfoStatsImage1,
	TitleText1,
};

export const components = {
	info_status_image1: InfoStatsImage1,
	title_text1: TitleText1,
};
